apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nbb-vobxu-go 
  janus-idp.io/tekton: nbb-vobxu-go
  backstage.io/kubernetes-id: nbb-vobxu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nbb-vobxu-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  