apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: nbb-vobxu-go-gitops
  description: This is GitOps manifest for nbb-vobxu-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: nbb-vobxu-go
    janus-idp.io/tekton: nbb-vobxu-go 
    backstage.io/kubernetes-id: nbb-vobxu-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:nbb-vobxu-go
